"""Add industry block

Revision ID: 0016595234e9
Revises: 8c56ad973b22
Create Date: 2026-03-01 23:57:40.694527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016595234e9'
down_revision: Union[str, Sequence[str], None] = '8c56ad973b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultancies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultancies_tenant_id'), 'consultancies', ['tenant_id'], unique=False)
    op.create_table('startup_involvements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('startup_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_involvements_tenant_id'), 'startup_involvements', ['tenant_id'], unique=False)
    op.create_table('technology_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('technology_name', sa.String(), nullable=False),
    sa.Column('partner', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_transfers_tenant_id'), 'technology_transfers', ['tenant_id'], unique=False)
    op.add_column('industry_collaborations', sa.Column('partner_name', sa.String(), nullable=False))
    op.add_column('industry_collaborations', sa.Column('project_title', sa.String(), nullable=False))
    op.add_column('industry_collaborations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('industry_collaborations', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('industry_collaborations', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('industry_collaborations_tenant_id_fkey'), 'industry_collaborations', type_='foreignkey')
    op.create_foreign_key(None, 'industry_collaborations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('industry_collaborations', 'company_name')
    op.drop_column('industry_collaborations', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_collaborations', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('industry_collaborations', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'industry_collaborations', type_='foreignkey')
    op.create_foreign_key(op.f('industry_collaborations_tenant_id_fkey'), 'industry_collaborations', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('industry_collaborations', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('industry_collaborations', 'link')
    op.drop_column('industry_collaborations', 'description')
    op.drop_column('industry_collaborations', 'project_title')
    op.drop_column('industry_collaborations', 'partner_name')
    op.drop_index(op.f('ix_technology_transfers_tenant_id'), table_name='technology_transfers')
    op.drop_table('technology_transfers')
    op.drop_index(op.f('ix_startup_involvements_tenant_id'), table_name='startup_involvements')
    op.drop_table('startup_involvements')
    op.drop_index(op.f('ix_consultancies_tenant_id'), table_name='consultancies')
    op.drop_table('consultancies')
    # ### end Alembic commands ###
