"""Add enterprise models for book chapters, media, industry, and full academic lifecycle

Revision ID: 0195e001682d
Revises: e8e75e67291e
Create Date: 2026-02-28 15:53:12.800272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0195e001682d'
down_revision: Union[str, Sequence[str], None] = 'e8e75e67291e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_services_tenant_id'), 'academic_services', ['tenant_id'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_tenant_id'), 'awards', ['tenant_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_tenant_id'), 'blog_posts', ['tenant_id'], unique=False)
    op.create_table('book_chapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('chapter_title', sa.String(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_chapters_tenant_id'), 'book_chapters', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('syllabus_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('datasets_software',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_software_tenant_id'), 'datasets_software', ['tenant_id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('thesis_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_tenant_id'), 'education', ['tenant_id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_tenant_id'), 'experience', ['tenant_id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_tenant_id'), 'gallery_images', ['tenant_id'], unique=False)
    op.create_table('industry_collaborations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_collaborations_tenant_id'), 'industry_collaborations', ['tenant_id'], unique=False)
    op.create_table('media_coverage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_outlet', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_coverage_tenant_id'), 'media_coverage', ['tenant_id'], unique=False)
    op.create_table('patents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('patent_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_tenant_id'), 'patents', ['tenant_id'], unique=False)
    op.create_table('postdocs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('current_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postdocs_tenant_id'), 'postdocs', ['tenant_id'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_tenant_id'), 'presentations', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('funding_agency', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('reviewer_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('journal_conference_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_roles_tenant_id'), 'reviewer_roles', ['tenant_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('thesis_title', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('is_alumni', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_table('tech_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('technology_name', sa.String(), nullable=False),
    sa.Column('industry_partner', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_transfers_tenant_id'), 'tech_transfers', ['tenant_id'], unique=False)
    op.create_table('working_papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_papers_tenant_id'), 'working_papers', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenants_custom_domain'), table_name='tenants')
    op.create_unique_constraint(None, 'tenants', ['custom_domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_custom_domain'), 'tenants', ['custom_domain'], unique=True)
    op.drop_index(op.f('ix_working_papers_tenant_id'), table_name='working_papers')
    op.drop_table('working_papers')
    op.drop_index(op.f('ix_tech_transfers_tenant_id'), table_name='tech_transfers')
    op.drop_table('tech_transfers')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_reviewer_roles_tenant_id'), table_name='reviewer_roles')
    op.drop_table('reviewer_roles')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_presentations_tenant_id'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_postdocs_tenant_id'), table_name='postdocs')
    op.drop_table('postdocs')
    op.drop_index(op.f('ix_patents_tenant_id'), table_name='patents')
    op.drop_table('patents')
    op.drop_index(op.f('ix_media_coverage_tenant_id'), table_name='media_coverage')
    op.drop_table('media_coverage')
    op.drop_index(op.f('ix_industry_collaborations_tenant_id'), table_name='industry_collaborations')
    op.drop_table('industry_collaborations')
    op.drop_index(op.f('ix_gallery_images_tenant_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_experience_tenant_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_tenant_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_datasets_software_tenant_id'), table_name='datasets_software')
    op.drop_table('datasets_software')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_book_chapters_tenant_id'), table_name='book_chapters')
    op.drop_table('book_chapters')
    op.drop_index(op.f('ix_blog_posts_tenant_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_awards_tenant_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_academic_services_tenant_id'), table_name='academic_services')
    op.drop_table('academic_services')
    # ### end Alembic commands ###
