"""Add outreach block

Revision ID: 11a77574db26
Revises: 7f2d64034d57
Create Date: 2026-03-02 00:34:44.638384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a77574db26'
down_revision: Union[str, Sequence[str], None] = '7f2d64034d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_articles_tenant_id'), 'blog_articles', ['tenant_id'], unique=False)
    op.create_table('gallery_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_tenant_id'), 'gallery_items', ['tenant_id'], unique=False)
    op.create_table('video_lectures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_lectures_tenant_id'), 'video_lectures', ['tenant_id'], unique=False)
    op.add_column('media_coverage', sa.Column('outlet_name', sa.String(), nullable=False))
    op.alter_column('media_coverage', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('media_coverage_tenant_id_fkey'), 'media_coverage', type_='foreignkey')
    op.create_foreign_key(None, 'media_coverage', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('media_coverage', 'media_outlet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_coverage', sa.Column('media_outlet', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media_coverage', type_='foreignkey')
    op.create_foreign_key(op.f('media_coverage_tenant_id_fkey'), 'media_coverage', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('media_coverage', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('media_coverage', 'outlet_name')
    op.drop_index(op.f('ix_video_lectures_tenant_id'), table_name='video_lectures')
    op.drop_table('video_lectures')
    op.drop_index(op.f('ix_gallery_items_tenant_id'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_index(op.f('ix_blog_articles_tenant_id'), table_name='blog_articles')
    op.drop_table('blog_articles')
    # ### end Alembic commands ###
