"""Add email and password to tenant

Revision ID: 1547d601e1f6
Revises: 08f5a2007677
Create Date: 2026-03-03 14:54:35.137089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1547d601e1f6'
down_revision: Union[str, Sequence[str], None] = '08f5a2007677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_column('tenants', 'hashed_password')
    op.drop_column('tenants', 'email')
    # ### end Alembic commands ###
