"""publication link + thumbnail

Revision ID: 1eaf31374084
Revises: fbdc7feeabc2
Create Date: 2026-03-06 18:20:12.461376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf31374084'
down_revision: Union[str, Sequence[str], None] = 'fbdc7feeabc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('external_link', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'thumbnail')
    op.drop_column('publications', 'external_link')
    # ### end Alembic commands ###
