"""Add working papers

Revision ID: 2b22412d1548
Revises: c7c64e649d87
Create Date: 2026-03-01 17:44:04.306999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b22412d1548'
down_revision: Union[str, Sequence[str], None] = 'c7c64e649d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_papers', sa.Column('abstract', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('working_papers', 'abstract')
    # ### end Alembic commands ###
