"""add profile link to cource

Revision ID: 36dcb33344b3
Revises: 80f5faa57f68
Create Date: 2026-03-08 18:38:50.363916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dcb33344b3'
down_revision: Union[str, Sequence[str], None] = '80f5faa57f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_materials', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_materials', 'thumbnail_url')
    # ### end Alembic commands ###
