"""add profile link to postdoct

Revision ID: 551981e8a244
Revises: 99186a941b5e
Create Date: 2026-03-08 17:47:15.415245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551981e8a244'
down_revision: Union[str, Sequence[str], None] = '99186a941b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('profile_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postdocs', 'profile_link')
    # ### end Alembic commands ###
