"""Add razorpay_subscription_id to tenants

Revision ID: 55e3f08b9df2
Revises: 0195e001682d
Create Date: 2026-02-28 23:05:12.340208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e3f08b9df2'
down_revision: Union[str, Sequence[str], None] = '0195e001682d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'razorpay_subscription_id')
    # ### end Alembic commands ###
