"""Add email and password to tenant

Revision ID: 5f6754930154
Revises: 781a464543b6
Create Date: 2026-03-03 18:39:48.802068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6754930154'
down_revision: Union[str, Sequence[str], None] = '781a464543b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Custom Module'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Custom Module'::character varying"))
    # ### end Alembic commands ###
