"""Add email and password to tenant

Revision ID: 781a464543b6
Revises: d6750b9f128c
Create Date: 2026-03-03 18:30:28.457884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781a464543b6'
down_revision: Union[str, Sequence[str], None] = 'd6750b9f128c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'modules',
    sa.Column('name', sa.String(), nullable=False, server_default="Custom Module")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'name')
    # ### end Alembic commands ###
