"""Add outputs block

Revision ID: 7f2d64034d57
Revises: 0016595234e9
Create Date: 2026-03-02 00:19:21.126916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2d64034d57'
down_revision: Union[str, Sequence[str], None] = '0016595234e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('total_citations', sa.Integer(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=False),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_metrics_tenant_id'), 'citation_metrics', ['tenant_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_tenant_id'), 'datasets', ['tenant_id'], unique=False)
    op.create_table('software_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_tools_tenant_id'), 'software_tools', ['tenant_id'], unique=False)
    op.add_column('postdocs', sa.Column('research_topic', sa.String(), nullable=True))
    op.add_column('postdocs', sa.Column('is_alumni', sa.Boolean(), nullable=True))
    op.add_column('postdocs', sa.Column('avatar_url', sa.String(), nullable=True))
    op.alter_column('postdocs', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('postdocs_tenant_id_fkey'), 'postdocs', type_='foreignkey')
    op.create_foreign_key(None, 'postdocs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('postdocs', 'current_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('current_position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'postdocs', type_='foreignkey')
    op.create_foreign_key(op.f('postdocs_tenant_id_fkey'), 'postdocs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('postdocs', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('postdocs', 'avatar_url')
    op.drop_column('postdocs', 'is_alumni')
    op.drop_column('postdocs', 'research_topic')
    op.drop_index(op.f('ix_software_tools_tenant_id'), table_name='software_tools')
    op.drop_table('software_tools')
    op.drop_index(op.f('ix_datasets_tenant_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_citation_metrics_tenant_id'), table_name='citation_metrics')
    op.drop_table('citation_metrics')
    # ### end Alembic commands ###
