"""add profile link to cource

Revision ID: 80f5faa57f68
Revises: 551981e8a244
Create Date: 2026-03-08 18:16:47.553575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f5faa57f68'
down_revision: Union[str, Sequence[str], None] = '551981e8a244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'thumbnail_url')
    # ### end Alembic commands ###
