"""Add activities block

Revision ID: 8c56ad973b22
Revises: 4b433c18450e
Create Date: 2026-03-01 23:40:49.629516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c56ad973b22'
down_revision: Union[str, Sequence[str], None] = '4b433c18450e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrative_roles_tenant_id'), 'administrative_roles', ['tenant_id'], unique=False)
    op.create_table('conference_organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('conference_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conference_organizations_tenant_id'), 'conference_organizations', ['tenant_id'], unique=False)
    op.create_table('teaching_philosophies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_philosophies_tenant_id'), 'teaching_philosophies', ['tenant_id'], unique=False)
    op.add_column('reviewer_roles', sa.Column('journal_name', sa.String(), nullable=False))
    op.add_column('reviewer_roles', sa.Column('publisher', sa.String(), nullable=True))
    op.alter_column('reviewer_roles', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviewer_roles', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('reviewer_roles_tenant_id_fkey'), 'reviewer_roles', type_='foreignkey')
    op.create_foreign_key(None, 'reviewer_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviewer_roles', 'journal_conference_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewer_roles', sa.Column('journal_conference_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviewer_roles', type_='foreignkey')
    op.create_foreign_key(op.f('reviewer_roles_tenant_id_fkey'), 'reviewer_roles', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('reviewer_roles', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewer_roles', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reviewer_roles', 'publisher')
    op.drop_column('reviewer_roles', 'journal_name')
    op.drop_index(op.f('ix_teaching_philosophies_tenant_id'), table_name='teaching_philosophies')
    op.drop_table('teaching_philosophies')
    op.drop_index(op.f('ix_conference_organizations_tenant_id'), table_name='conference_organizations')
    op.drop_table('conference_organizations')
    op.drop_index(op.f('ix_administrative_roles_tenant_id'), table_name='administrative_roles')
    op.drop_table('administrative_roles')
    # ### end Alembic commands ###
