"""add department and profile link to students

Revision ID: 99186a941b5e
Revises: b0423cf22c25
Create Date: 2026-03-06 22:20:55.643535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99186a941b5e'
down_revision: Union[str, Sequence[str], None] = 'b0423cf22c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.String(), nullable=True))
    op.add_column('students', sa.Column('profile_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'profile_link')
    op.drop_column('students', 'department')
    # ### end Alembic commands ###
