"""chapters add external link thumbnail

Revision ID: b0423cf22c25
Revises: fa01597f03f5
Create Date: 2026-03-06 21:52:37.700104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0423cf22c25'
down_revision: Union[str, Sequence[str], None] = 'fa01597f03f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_chapters', sa.Column('file_link', sa.String(), nullable=True))
    op.add_column('book_chapters', sa.Column('external_link', sa.String(), nullable=True))
    op.add_column('book_chapters', sa.Column('thumbnail', sa.String(), nullable=True))
    op.drop_column('book_chapters', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_chapters', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('book_chapters', 'thumbnail')
    op.drop_column('book_chapters', 'external_link')
    op.drop_column('book_chapters', 'file_link')
    # ### end Alembic commands ###
