"""Add research interests

Revision ID: c7c64e649d87
Revises: 7a971aca8c9e
Create Date: 2026-03-01 17:29:30.563285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c64e649d87'
down_revision: Union[str, Sequence[str], None] = '7a971aca8c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_interests', sa.Column('media_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_interests', 'media_url')
    # ### end Alembic commands ###
