"""Add patents table

Revision ID: ca6b57231994
Revises: 2b22412d1548
Create Date: 2026-03-01 21:50:19.113258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6b57231994'
down_revision: Union[str, Sequence[str], None] = '2b22412d1548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patents', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('patents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('patents_tenant_id_fkey'), 'patents', type_='foreignkey')
    op.create_foreign_key(None, 'patents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patents', type_='foreignkey')
    op.create_foreign_key(op.f('patents_tenant_id_fkey'), 'patents', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('patents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('patents', 'description')
    # ### end Alembic commands ###
