"""Add books and chapters

Revision ID: cc466bcaed25
Revises: ca6b57231994
Create Date: 2026-03-01 22:04:48.033318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc466bcaed25'
down_revision: Union[str, Sequence[str], None] = 'ca6b57231994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_chapters', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('book_chapters', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book_chapters', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('book_chapters_tenant_id_fkey'), 'book_chapters', type_='foreignkey')
    op.create_foreign_key(None, 'book_chapters', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('books', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('books', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('books_tenant_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_tenant_id_fkey'), 'books', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('books', 'link')
    op.drop_constraint(None, 'book_chapters', type_='foreignkey')
    op.create_foreign_key(op.f('book_chapters_tenant_id_fkey'), 'book_chapters', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('book_chapters', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book_chapters', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('book_chapters', 'link')
    # ### end Alembic commands ###
