"""Add email and password to tenant

Revision ID: d6750b9f128c
Revises: 1547d601e1f6
Create Date: 2026-03-03 18:29:05.330188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6750b9f128c'
down_revision: Union[str, Sequence[str], None] = '1547d601e1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('modules_key_key'), 'modules', type_='unique')
    op.create_index(op.f('ix_modules_key'), 'modules', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_key'), table_name='modules')
    op.create_unique_constraint(op.f('modules_key_key'), 'modules', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
