"""books add file external link thumbnail

Revision ID: fa01597f03f5
Revises: 1eaf31374084
Create Date: 2026-03-06 21:38:00.039951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa01597f03f5'
down_revision: Union[str, Sequence[str], None] = '1eaf31374084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_link', sa.String(), nullable=True))
    op.add_column('books', sa.Column('external_link', sa.String(), nullable=True))
    op.add_column('books', sa.Column('thumbnail', sa.String(), nullable=True))
    op.drop_column('books', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'thumbnail')
    op.drop_column('books', 'external_link')
    op.drop_column('books', 'file_link')
    # ### end Alembic commands ###
