"""Add facebook and instagram to profile

Revision ID: fbdc7feeabc2
Revises: 248c0732b94c
Create Date: 2026-03-06 17:06:44.968456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdc7feeabc2'
down_revision: Union[str, Sequence[str], None] = '248c0732b94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('instagram', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'instagram')
    op.drop_column('profiles', 'facebook')
    # ### end Alembic commands ###
